# action.yml
name: 'dvc-action-docker'
description: ''
inputs:
  github_token: 
    required: true

  dvc_pull:
    required: false
    default: true

  repro_targets:
    required: false
    default: 'Dvcfile'

  metrics_diff_targets:
    required: false

  metrics_format:
    required: false
    default: '0[.][0000000]'

  rev:
    required: false
    default: 'origin/master'
    
runs:
  using: 'docker'
  image: 'docker://davidgortega/dvc:0.1.6'
